###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    redis:
      image: redis:alpine
      container_name: zride-redis

    mariadb:
      image: mariadb:10.4
      container_name: zride-mariadb
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=zride
        - MYSQL_DATABASE=zride
        - MYSQL_USER=zride1234
        - MYSQL_PASSWORD=zfortzrizeproject1234
      ports:
        - "8086:3306"

    webserver:
      image: nginx:alpine
      container_name: zride-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "80:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: zride-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini

